name: Nightly Submodule Update

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-submodule:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true
      
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
      
      - name: Update support-matrix submodule
        run: |
          git submodule update --remote --recursive support-matrix
      
      - name: Commit and push if submodule has changed
        run: |
          if git diff --quiet; then
            echo "No changes to commit"
          else
            git add support-matrix
            git commit -m "chore: update support-matrix submodule [automated]"
            git push
          fi
